const Promise = require('bluebird');
const assert = require('assert');
const { isRedis } = require('../../asserts/redis');
const isValidId = require('../../asserts/id');
const isNotEmptyString = require('../../asserts/string-not-empty');

const getInternalData = require('../../userData/get-internal-data');

const {
  USERS_ALIAS_TO_ID,
  USERS_SSO_TO_ID,
  USERS_USERNAME_TO_ID,
  USERS_INDEX,
  USERS_PUBLIC_INDEX,
  USERS_DATA,
  USERS_TOKENS,
} = require('../../../constants');

/**
 * Class handles User data operations using Redis backend
 */
class User {
  /**
   * @param {ioredis|Pipeline}redis
   */
  constructor(redis) {
    assert(isRedis(redis), 'must be a valid redis instance');
    this.redis = redis;
  }

  /**
   * Generates Redis Hash Key storing user data
   * @param {String|Number}userId
   * @returns {string}
   */
  static getUserDataKey(userId) {
    assert(isValidId(userId), 'must be valid user id');
    return `${userId}!${USERS_DATA}`;
  }

  /**
   * Flush caches generated by `redis-fsort`
   * @returns {Promise<*>}
   */
  flushCaches() {
    const now = Date.now();
    return Promise.all([
      this.redis.fsortBust(USERS_INDEX, now),
      this.redis.fsortBust(USERS_PUBLIC_INDEX, now),
    ]);
  }

  /**
   * Returns User data
   * @param {String|Number}userId
   */
  getData(userId) {
    assert(isValidId(userId), 'must be valid user id');
    return getInternalData.call({ redis: this.redis }, userId);
  }

  /**
   * Deletes User and associated data
   * @param user
   * @param {String|Number}user.id
   * @param {String}user.username
   * @param {String}user.alias
   * @param {String[]}user.ssoIds
   * @param {ioredis|Pipeline} [redis]
   * @returns {any}
   */
  delete({ id, username, alias, ssoIds }, redis = this.redis) {
    assert(isRedis(redis), 'must be a valid redis instance');
    assert(isValidId(id), 'must be valid user id');
    assert(isNotEmptyString(username), 'must be valid alias');

    const scriptKeys = [
      USERS_ALIAS_TO_ID, USERS_USERNAME_TO_ID, USERS_SSO_TO_ID,
      USERS_PUBLIC_INDEX, USERS_INDEX, USERS_TOKENS,
      User.getUserDataKey(id),
    ];
    const luaScript = `
      ${alias === undefined ? '' : `redis.call("HDEL", KEYS[1], '${alias}', '${alias.toLowerCase()}')`}
      redis.call("HDEL", KEYS[2], '${username}')
      ${ssoIds.length > 0 ? `redis.call("HDEL", KEYS[3], ${ssoIds.map((uid) => `'${uid}'`).join(',')})` : ''}
      redis.call("SREM", KEYS[4], '${id}')
      redis.call("SREM", KEYS[5], '${id}')
      redis.call("HDEL", KEYS[6], '${id}')
      redis.call("DEL", KEYS[7])
    `;
    return redis.eval(luaScript, scriptKeys.length, ...scriptKeys);
  }
}

module.exports = User;
